apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30008
        hostPort: 30008
        listenAddress: 127.0.0.1

      - containerPort: 8080
        hostPort: 8080
        listenAddress: 127.0.0.1