logging:
  level:
    org.springframework: DEBUG

management:
  health:
    kubernetes:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  readinessstate:
    enabled: true
  livenessstate:
    enabled: true


spring:
  cloud:
    kubernetes:
      secrets:
        enabled: false