apiVersion: v1
kind: Service
metadata:
  name: conditional-on-platform
  namespace: spring-k8s
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30008
    name: http
  selector:
    app: conditional-on-platform
    type: conditional-on-platform