apiVersion: skaffold/v2beta17
kind: Config
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
    - image: zero-x/spring-cloud-kubernetes/liq-cassandra
      custom:
        buildCommand: ./build.sh
  local:
    useDockerCLI: false
    useBuildkit: false
    push: false


deploy:
  helm:
    releases:
      - name: liq-cassandra
        chartPath: src/main/helm
        artifactOverrides:
          # skaffold will override this with a different tag
          image: zero-x/spring-cloud-kubernetes/liq-cassandra
        valuesFiles:
          - src/main/helm/values.yaml
        wait: true
        setValues:
          namespace: spring-k8s
