apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-update-job"
  namespace: spring-k8s
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}-cassandra-update-job"
      namespace: spring-k8s
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      restartPolicy: Never
      volumes:
        - name: liquibase-changelog-config-map
          configMap:
            name: liquibase-changelog-config-map
            defaultMode: 0777
      containers:
        - name: pre-install-upgrade-job
          volumeMounts:
            - name: liquibase-changelog-config-map
              mountPath: /liquibase-changelog-file
          image: "lq/liquibase-cassandra:1.0.0"
          command: ["/bin/bash"]
          args:
            - "-c"
            # hack for : https://github.com/liquibase/liquibase/issues/2104
            - "cp liquibase-changelog-file/{{ printf "%s" .Values.liquibase.file }} .; ./liquibase-cassandra.sh --username {{ .Values.liquibase.username }} --password {{ .Values.liquibase.username }} --url {{ .Values.liquibase.url | squote }} --file {{ printf "%s" .Values.liquibase.file }} --table-name {{ printf "%s-database-changes" .Chart.Name }}"