apiVersion: v1
kind: ConfigMap
metadata:
  name: "liquibase-changelog-config-map"
  namespace: spring-k8s
  annotations:
    helm.sh/hook: pre-install, pre-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
    helm.sh/hook-weight: "1"
data:
{{ (.Files.Glob "resources/databaseChangelog.json").AsConfig | indent 2 }}