#kubectl get rolebindings --all-namespaces | grep config
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: spring-k8s
  name: liq-cassandra-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: liq-cassandra-cluster-role
subjects:
  - kind: ServiceAccount
    name: liq-cassandra-service-account
    namespace: spring-k8s
