apiVersion: v1
kind: Service
metadata:
  name: liq-cassandra
  namespace: spring-k8s
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30008
    name: http
  selector:
    app: liq-cassandra
    type: liq-cassandra